### ISSUE TITLE
Setting System

### ISSUE THREAD

**Issue by phumberdroz** [TaskForce47/Tf47-Core-Scripts#8]
Hey ich wollte mal fragen was ihr so für Ideen habt wie wir das mit Einstellungen handhaben wollen?

Jeder Bereich hat ja seine eigenen Einstellungen also wollen wir eher eine große Config haben oder mehrere Kleine?

@TheNiner @christian2526 @4Lucke @mindbl4ster @Sonic47

**Comment by 4Lucke** [comment]
würde die config mit bei der arma config speichern und dann noch in Unterklassen verteilen.

**Comment by TheWillard** [comment]
Mir ist es eigentlich egal, wäre nur gut wenn Leute wie @JohnHunter47 damit klar kommen (nichts für ungut John)

**Comment by mindbl4ster** [comment]
gibt viele varianten, aber ich wär für eine gut dokumentiere alles umfassende config.hpp.

einfach dass man alle optionen in einem doc hat und nicht wieder alles suchen muss

**Comment by mindbl4ster** [comment]
done #10
